active_set: dcase2022_baseline

sets:
  # DCASE2021 baseline, subtask A
  # ================================
  - set_id: dcase2022_baseline
    desciption: DCASE2022 baseline

    dataset:
      method: baseline_development

    learner:
      method: cnn

defaults:
  flow:
    learning: true
    testing: true
    evaluation: true
    calculate_model_size: true

  general:
    overwrite: yes                        # Overwrite previously stored data
    active_fold_list: !!null

  path:
    dataset: dataset
    log: log/
    application:
      base: system/task1
      learner: learner
      recognizer: recognizer
      evaluator: evaluator

  features:
    path: ../features_all.h5

  dataset:
    method: baseline_development

  dataset_method_parameters:
    baseline_development:
      dataset: TAUUrbanAcousticScenes_2022_Mobile_DevelopmentSet
      evaluation_mode: folds

    baseline_evaluation:
      dataset: TAUUrbanAcousticScenes_2022_Mobile_EvaluationSet
      evaluation_mode: full

  learner_method_parameters:
    cnn:
      iteration: 1

      random_seed: 0
      keras_profile: cuda0_fast
      backend: tensorflow

      validation_set:
        enable: true
        validation_amount: 0.3
        balancing_mode: class
        seed: 0

      data:
        data_format: channels_last
        target_format: single_target_per_sequence

      generator:
        enable: false

      model:
        constants:
          CONVOLUTION_INIT: glorot_uniform
          CONVOLUTION_KERNEL_SIZE: 7
          CONVOLUTION_ACTIVATION: relu
          CONVOLUTION_DROPOUT: 0.3
          CONVOLUTION_BORDER_MODE: same

          DATA_FORMAT: channels_last

        config:
          # CNN layer 1
          # ====================================
          # Convolution layer
          - class_name: Conv2D
            config:
              input_shape:
                - FEATURE_VECTOR_LENGTH   # data_axis
                - INPUT_SEQUENCE_LENGTH   # time_axis
                - 1                       # sequence_axis
              filters: 16
              kernel_size: CONVOLUTION_KERNEL_SIZE
              padding: CONVOLUTION_BORDER_MODE
              kernel_initializer: CONVOLUTION_INIT
              data_format: DATA_FORMAT

          # Batch normalization
          - class_name: BatchNormalization
            config:
              axis: -1

          # Detection layer
          - class_name: Activation
            config:
              activation: CONVOLUTION_ACTIVATION
          # CNN layer 2
          # ====================================
          # Convolution layer
          - class_name: Conv2D
            config:
              input_shape:
                - FEATURE_VECTOR_LENGTH   # data_axis
                - INPUT_SEQUENCE_LENGTH   # time_axis
                - 1                       # sequence_axis
              filters: 16
              kernel_size: CONVOLUTION_KERNEL_SIZE
              padding: CONVOLUTION_BORDER_MODE
              kernel_initializer: CONVOLUTION_INIT
              data_format: DATA_FORMAT

          # Batch normalization
          - class_name: BatchNormalization
            config:
              axis: -1

          # Detection layer
          - class_name: Activation
            config:
              activation: CONVOLUTION_ACTIVATION

          # Pooling layer
          - class_name: MaxPooling2D
            config:
              pool_size:
                - 5
                - 5
              data_format: DATA_FORMAT

          # Drop out layer
          - class_name: Dropout
            config:
              rate: CONVOLUTION_DROPOUT

          # CNN layer 3
          # ====================================
          # Convolution layer
          - class_name: Conv2D
            config:
              filters: 32
              kernel_size: CONVOLUTION_KERNEL_SIZE
              padding: CONVOLUTION_BORDER_MODE
              kernel_initializer: CONVOLUTION_INIT
              data_format: DATA_FORMAT

          # Batch normalization
          - class_name: BatchNormalization
            config:
              axis: -1

          # Detection layer
          - class_name: Activation
            config:
              activation: CONVOLUTION_ACTIVATION

          # Pooling layer
          - class_name: MaxPooling2D
            config:
              pool_size:
                - 4
                - 10
              data_format: DATA_FORMAT

          # Drop out layer
          - class_name: Dropout
            config:
              rate: CONVOLUTION_DROPOUT

          # Flatten
          # ====================================
          - class_name: Flatten

          # Fully connected layer
          # ====================================
          - class_name: Dense
            config:
              units: 100
              kernel_initializer: uniform
              activation: relu

          - class_name: Dropout
            config:
              rate: 0.3

          # Output layer
          # ====================================
          - class_name: Dense
            config:
              units: CLASS_COUNT
              kernel_initializer: uniform
              activation: softmax

      compile:
        loss: categorical_crossentropy
        metrics:
          - categorical_accuracy

      optimizer:
        class_name: Adam

      fit:
        epochs: 200
        batch_size: 64
        shuffle: true

      callbacks:
        StasherCallback:
          monitor: val_categorical_accuracy
          initial_delay: 50

  recognizer:
    collapse_probabilities:
      enable: true
      operator: sum

    frame_binarization:
      enable: true
      type: frame_max
